### ISSUE TITLE
Fails to expand shorthands with css custom properties

### ISSUE THREAD

**Issue by aleray** [johnotander/postcss-shorthand-expand#2]
Hi,

the following code fails to be expanded:

``` css
:root {
    --my-color: red;
}

.test {
    border: 1px solid var(--my-color);
}
```

and raises the error:

`postcss-shorthand-expand failed to expand a property border: 1px solid var(--my-color);
`

Do you see a fix for that?

Thanks
