### ISSUE TITLE
Partials are not proccessed

### ISSUE THREAD

**Issue by gusbueno** [johnotander/postcss-shorthand-expand#3]
If youy have a .scss file with same `@import` the imported file is not proccessed to shorthand its properties. Example:
Input file:
```scss
// _partial.scss
.partial {
  background: red;
}
```
```scss
// main.scss
@import "partial";

.main {
  background: blue;
}
```

Output:
```css
.partial {
  background: red;
}

.main {
  background-color: blue:
}
```

Is there any way to avoid this?
